import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import tailwindIntegration from "@astrojs/tailwind";
import AuthProvider from "./components/AuthProvider";
import Header from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
      </AuthProvider>
    </html>
  );
}
